// List of characters
export const FETCH_CHARACTERS_REQUEST = 'FETCH_CHARACTERS_REQUEST';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAILURE = 'FETCH_CHARACTERS_FAILURE';
export const SET_CHARACTERS_PAGE = 'SET_CHARACTERS_PAGE';

// Details of a character
export const FETCH_CHARACTERS_DETAILS_REQUEST = 'FETCH_CHARACTERS_DETAILS_REQUEST';
export const FETCH_CHARACTERS_DETAILS_SUCCESS = 'FETCH_CHARACTERS_DETAILS_SUCCESS';
export const FETCH_CHARACTERS_DETAILS_FAILURE = 'FETCH_CHARACTERS_DETAILS_FAILURE';
